# different ways of creating numpy

In [1]:
import numpy as np

In [2]:
var_1=np.array([1,2,3,4])
print(var_1)

[1 2 3 4]


In [5]:
var_2=np.array([[1,2,3],[5,6,7]])
print(var_2)

[[1 2 3]
 [5 6 7]]


In [6]:
#array of zeros:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#array of ones:
np.ones((2,2),dtype="int")

array([[1, 1],
       [1, 1]])

In [10]:
#array of random elements:
np.random.rand(4,4)

array([[0.17648021, 0.34178004, 0.05026513, 0.24473755],
       [0.89071803, 0.50555028, 0.353105  , 0.46196717],
       [0.70524652, 0.93175967, 0.60125141, 0.20085902],
       [0.51199135, 0.55362542, 0.9439483 , 0.27457876]])

In [12]:
np.random.randn(4,4)

array([[-4.34186365e-01,  7.69640026e-01,  2.62957713e+00,
        -1.86133972e+00],
       [ 2.52030290e-01, -1.70823427e-03,  1.22358834e-01,
         1.09037257e+00],
       [-2.18780418e+00,  2.30716381e-01,  1.42343871e+00,
        -4.22365212e-01],
       [ 5.71182864e-01,  7.50766025e-01, -7.93426569e-01,
        -3.34094829e-01]])

In [17]:
np.random.seed(4)
x_1=np.random.randint(low=50,high=100,size=(4,4))

# slicing and indexing :

In [18]:
x_1

array([[96, 55, 51, 90],
       [73, 58, 59, 89],
       [95, 80, 90, 86],
       [94, 88, 92, 53]], dtype=int32)

In [27]:
x_1[1,1]
#indexing=[rows,columns]

TypeError: list indices must be integers or slices, not tuple

In [28]:
arr=np.array([10,20,30,40,50,60])

In [29]:
print(arr[1:4])

[20 30 40]


In [33]:
arr[2]=40
print(arr)
print(arr>50)

[10 20 40 40 50 60]
[False False False False False  True]


In [34]:
print(arr[arr>50])

[60]


TypeError: Field elements must be 2- or 3-tuples, got '5'

In [39]:
arr = np.array([10,20,30])

new_arr = np.append(arr,40)

print(new_arr)

[10 20 30 40]
