# numpy=====numarical python

In [2]:
import numpy as np

In [8]:
data=np.array([1,2,3])
print(data)
#one dimensinal array

[1 2 3]


In [5]:
array_2=np.array((30,40,50))
print(array_2)


[30 40 50]


In [7]:
array_3=np.array(([1,2,3],[4,5,6]))
print(array_3)
#two square brackets two dimensial array

[[1 2 3]
 [4 5 6]]


In [23]:
arr=np.random.randint(1,11,5)
print(arr)


[6 4 3 3 5]


In [26]:
marks=np.array([55,78,90,45,88])
print("total =",marks.sum())
print("averrage =",marks.mean())
print("highest =",marks.max())

total = 356
averrage = 71.2
highest = 90


In [32]:
np.array([1,2,3,4],dtype="float")

array([1., 2., 3., 4.])

# mini project : student marks analyzer

In [50]:
marks=np.array([78, 65, 90, 45, 88, 72, 95, 60])
print("students marks :",marks)
print('total marks of all students :',marks.sum())
print("average marks of students :",marks.mean())
print("average marks of students :",marks.max())
print("average marks of students :",marks.min())
avg=marks[marks>marks.mean()]
print(avg)
print('no of students passed: ',(50<marks))




students marks : [78 65 90 45 88 72 95 60]
total marks of all students : 593
average marks of students : 74.125
average marks of students : 95
average marks of students : 45
[78 90 88 95]
no of students passed:  [ True  True  True False  True  True  True  True]


# mini project2: cricket score analyzer


In [79]:
india=np.array([90,98,100,56,35,22])
pakistan=np.array([56,46,35,35,28,100])
print("india vs pakistan")
print("india score :",india.sum())
print("pakistan score :",pakistan.sum())
print("india won by ", india.sum()-pakistan.sum(),"runs")
print("score card :")
print("most runs: virat kohli :",india.max() )
print("virat kohli average:",india[2].mean())

     

india vs pakistan
india score : 401
pakistan score : 300
india won by  101 runs
score card :
most runs: virat kohli : 100
virat kohli average: 100.0
