In [7]:

import numpy as np

In [8]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
b=np.random.random((2,4))
print(b)

[[0.73438749 0.83828845 0.92262971 0.10427911]
 [0.97623583 0.8172975  0.40233132 0.23425012]]


In [12]:
 c=np.random.randint(10,100,(3,5))
 print(c)

[[69 88 58 68 94]
 [36 66 43 12 32]
 [46 56 90 86 87]]
